import { build } from 'esbuild';

await build({
    entryPoints: ['src/card.js'],
    outfile: 'intercom-camera-card.js',
    bundle: true,
    minify: true,
    format: 'esm',
    target: 'es2022',
    external: ['/webrtc/*'],
    banner: { js: '// Generated from src/card.js. Run npm run build; do not edit this file.' },
    legalComments: 'eof',
});
